openmpf/openmpf-docker

.gitignore, README.md, mpf_build/Dockerfile
Docker context instead of cloned during
the build. This allows for more granular
controll of what source code is used in
the docker image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/4)
=> Change source code to be copied in

openmpf_build/docker-entrypoint.sh, openmpf_runtime/node_manager/docker-entrypoint.sh, openmpf_runtime/workflow_manager/docker-entrypoint.sh, scripts/docker-remove-images.sh, scripts/docker-swarm-remove-images.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/8)
=> Custom steps

openmpf_build/docker-entrypoint.sh, openmpf_runtime/workflow_manager/docker-entrypoint.sh
https://github.com/openmpf/openmpf/issues/720
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/11)
=> Update the target segment size to 1000

CONTRIBUTING.md, README.md, SWARM.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/15)
=> Add CONTRIBUTING.md.

SWARM.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/16)
=> Added steps for configuring NVIDIA runtime.

openmpf_build/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/17)
=> Fixing libuuid.so symlink issue.

Jenkinsfile, openmpf_build/docker-entrypoint.sh, openmpf_runtime/node_manager/Dockerfile, openmpf_runtime/workflow_manager/Dockerfile, openmpf_runtime/workflow_manager/Dockerfile-test, openmpf_runtime/workflow_manager/docker-entrypoint-test.sh, openmpf_runtime/workflow_manager/docker-entrypoint.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/18)
=> Custom config

openmpf_build/Dockerfile, openmpf_runtime/node_manager/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/21)
=> Update Docker openmpf_build image to build ImageMagick 6.9.10 (#776)

README.md, SWARM.md, openmpf_runtime/workflow_manager/docker-entrypoint.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/22)
=> Preserve custom properties

README.md, SWARM.md, openmpf_runtime/workflow_manager/docker-entrypoint.sh
* Updated docs to explain node auto configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/23)
=> Preserve custom properties (#22)

Jenkinsfile, NOTICE, active_mq/Dockerfile, active_mq/activemq.xml, openmpf_build/Dockerfile, openmpf_build/docker-entrypoint.sh, openmpf_runtime/node_manager/Dockerfile, openmpf_runtime/node_manager/docker-entrypoint.sh, openmpf_runtime/node_manager/setup-python-component-venv.py, openmpf_runtime/workflow_manager/Dockerfile, openmpf_runtime/workflow_manager/Dockerfile-test, openmpf_runtime/workflow_manager/docker-entrypoint-test.sh, openmpf_runtime/workflow_manager/docker-entrypoint.sh, scripts/docker-compose-cleanup.sh, scripts/docker-compose-load.sh, scripts/docker-compose-save.sh, scripts/docker-generate-compose-files.sh, scripts/docker-registry-remove-images.py, scripts/docker-remove-images.sh, scripts/docker-swarm-clean-shared-volume.sh, scripts/docker-swarm-cleanup.sh, scripts/docker-swarm-logs.sh, scripts/docker-swarm-remove-images.sh, scripts/docker-swarm-run-on-all-nodes.sh, scripts/docker-system-prune.sh, templates/docker-compose-test.yml, templates/docker-compose.yml, templates/swarm-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/25)
=> Updated copyright year to 2019.

openmpf_runtime/python_executor/Dockerfile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/29)
=> Preserve symlinks when COPYing shared libraries in to openmpf_python_executor

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/31)
=> Now force-removing dangling <none> images.

openmpf_build/Dockerfile, openmpf_runtime/workflow_manager/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/33)
=> Now install Ansible via yum. Set gather_timeout.

scripts/docker-registry-remove-images.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/36)
=> Improve error handling. Show dry run summary. Show creation dates.

openmpf_runtime/python_executor/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/40)
=> Added missing slash.

openmpf_build/docker-entrypoint.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/35)
=> Remove non-Docker build artifacts from build container.

scripts/docker-swarm-cleanup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/42)
=> Clarify volume removal message.

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/43)
=> Now handles git tags and commit SHAs.

Jenkinsfile, openmpf_build/docker-entrypoint.sh, openmpf_build/run-gtests.sh, openmpf_build/run-mvn-tests.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/46)
=> Remove sudo from Jenkinsfile.

openmpf_build/Dockerfile, openmpf_runtime/node-manager/Dockerfile, openmpf_runtime/workflow-manager/Dockerfile
https://github.com/openmpf/openmpf/issues/927
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/45)
=> Remove codecs compilation when building ffmpeg

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/48)
=> Allow users to configure a Docker registry path.

openmpf_build/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/51)
=> Install ghostscript to allow ImageMagick to extract images from PDFs.

openmpf_build/Dockerfile, openmpf_runtime/cpp-component-build/Dockerfile, openmpf_runtime/python-executor/Dockerfile-child-example, openmpf_runtime/python-executor/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/49)
=> Update OpenCV to 3.4.7

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/52)
=> Add option to build with "--no-cache".

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/53)
=> Fix bug "Cannot invoke method toBoolean() on null object" for build_no_cache variable.

README.md, docker-compose.users.yml, openmpf_runtime/workflow-manager/docker-entrypoint.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/55)
=> Add Docker secret for user.properties.

Jenkinsfile, README.md, docker-compose.users.yml, openmpf_build/run-gtests.sh, openmpf_build/run-mvn-tests.sh, openmpf_runtime/workflow_manager/docker-entrypoint.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/56)
=> Add Docker secret for user.properties file.

.env.tpl, Jenkinsfile, SWARM.md, activemq/docker-entrypoint.sh, docker-compose.core.yml, openmpf_build/Dockerfile, openmpf_build/docker-entrypoint.sh, openmpf_build/run-mvn-tests.sh, openmpf_runtime/node-manager/Dockerfile, openmpf_runtime/workflow-manager/Dockerfile, openmpf_runtime/workflow-manager/docker-entrypoint.sh, scripts/docker-swarm-cleanup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/60)
=> Merge postgres to develop

openmpf_build/Dockerfile, openmpf_runtime/node-manager/Dockerfile, openmpf_runtime/python-executor/Dockerfile, openmpf_runtime/workflow-manager/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/62)
=> Hf merge/fix clair issues

Jenkinsfile, docker-compose.core.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/63)
=> Use redis:alpine instead of redis:latest because it passes clair scan

Jenkinsfile, docker-compose.core.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/64)
=> hf-merge/use redis alpine

openmpf_build/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/66)
=> Update Tomcat version so we can use new version of hibernate.

Jenkinsfile, README.md, docker-compose.elk.yml, docker-compose.integration.test.yml, kibana/Dockerfile, kibana/docker-entrypoint.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/65)
=> Add support for viewing logs in kibana.

scripts/docker-retag-all.sh, scripts/docker-retag-push-images.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/67)
=> Add docker-retag-all.sh.

README.md, docker-compose.components.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/71)
=> Change component restart policy and document RESTRICT_MEDIA_TYPES

openmpf_build/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/73)
=> Build opencv_contrib

Jenkinsfile, openmpf_runtime/workflow_manager/Dockerfile, openmpf_runtime/workflow_manager/docker-entrypoint.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/79)
=> Support user-defined labels.

Jenkinsfile, docker-compose.components.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/80)
=> Add AzureOcr to docker-compose.components.yml

openmpf_build/Dockerfile, openmpf_runtime/node_manager/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/86)
=> Fix ImageMagick package names in yum commands.

.env.tpl, Jenkinsfile, README.md
Issue: https://github.com/openmpf/openmpf/issues/1092
- https://github.com/openmpf/openmpf-projects/pull/5
- https://github.com/openmpf/openmpf-docker/pull/88
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/88)
=> Add openmpf-docker to openmpf-projects

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/89)
=> Update minor version of JDK

openmpf_build/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/91)
=> Update OpenCV build to support webp images.

openmpf_build/Dockerfile, openmpf_runtime/node_manager/Dockerfile
- https://github.com/openmpf/openmpf-components/pull/157
- https://github.com/openmpf/openmpf-docker/pull/93
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/93)
=> Fix CUDA install

components/cpp_executor/Dockerfile, components/java_executor/Dockerfile, components/python_component_build/Dockerfile, components/python_executor/Dockerfile, openmpf_build/Dockerfile, workflow_manager/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/97)
=> Fix build cache issue caused by .pyc files.

workflow_manager/Dockerfile, workflow_manager/docker-entrypoint.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/85)
=> Use $MPF_CA_CERTS environment variable to import CA certs.

docker-compose.components.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/103)
=> Azure Speech Component

Jenkinsfile, docker-compose.components.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/107)
=> Merge in pre-build hook changes.

SWARM.md, scripts/docker-swarm-cleanup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/109)
=> Simplify docker-swarm-cleanup.sh

SWARM.md, scripts/docker-swarm-cleanup.sh
* Simplify docker-swarm-cleanup.sh
* Update SWARM.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/110)
=> Simplify docker-swarm-cleanup.sh (#109)

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/115)
=> Update link to NVIDIA runtime installation instructions. (#114)

docker-compose.components.yml
Co-authored-by: jrobble <jrobble@mitre.org>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/119)
=> Add TRTIS detection component and server (#81)

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/116)
=> Add submodule option to Jenkins build, and allow some components to be only built, not run.

docker-compose.components.yml
Resolves openmpf/openmpf#1161.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/117)
=> Adding Azure Form Recognizer component to docker-compose.components.yml

markup/Dockerfile, openmpf_build/Dockerfile, workflow_manager/Dockerfile
Resolves https://github.com/openmpf/openmpf/issues/1130
Resolves https://github.com/openmpf/openmpf/issues/1028
Associated PR: https://github.com/openmpf/openmpf/pull/1189
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/123)
=> Add support for heic files and Apple-optimized PNGs.

openmpf_build/Dockerfile, workflow_manager/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/124)
=> Install "file" command.

docker-compose.components.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/122)
=> dockerizing keyword tagger

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/126)
=> Handle DockerHub pull limit

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/127)
=> Add missing argument to docker.withRegistry

docker-compose.components.yml
Issue: https://github.com/openmpf/openmpf/issues/1169
- https://github.com/openmpf/openmpf-components/pull/185
- https://github.com/openmpf/openmpf-docker/pull/120
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/120)
=> Add azure_translation

docker-compose.components.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/131)
=> Use MPF_PROP_ in docker-compose.components.yml

Jenkinsfile, docker-compose.components.yml, scripts/docker-compose-save.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/134)
=> Use yq:3 and update MPF_PROP_ comments.

components/python_component_build/Dockerfile, docker-compose.components.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/136)
=> Add entry for Ocv Yolo

markup/Dockerfile, openmpf_build/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/137)
=> Support icons in markup.

openmpf_build/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/139)
=> Limit ffmpeg threads

components/cpp_component_build/Dockerfile, components/cpp_executor/Dockerfile, components/java_component_build/Dockerfile, components/java_executor/Dockerfile, components/python/Dockerfile, markup/Dockerfile, openmpf_build/Dockerfile, workflow_manager/Dockerfile
Resolves: openmpf/openmpf#1307
- https://github.com/openmpf/openmpf/pull/1310
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/102
- https://github.com/openmpf/openmpf-python-component-sdk/pull/45
- https://github.com/openmpf/openmpf-docker/pull/141
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/141)
=> Support VFR videos

components/cpp_component_build/Dockerfile, components/cpp_executor/Dockerfile, components/java_component_build/Dockerfile, components/java_executor/Dockerfile, components/python/Dockerfile, markup/Dockerfile, openmpf_build/Dockerfile, workflow_manager/Dockerfile
Merges https://github.com/openmpf/openmpf-docker/pull/141 in to develop
Issue: https://github.com/openmpf/openmpf/issues/1307
- https://github.com/openmpf/openmpf/pull/1314
- https://github.com/openmpf/openmpf-python-component-sdk/pull/47
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/104
- https://github.com/openmpf/openmpf-docker/pull/143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/143)
=> Support VFR videos (#141)

markup/Dockerfile, openmpf_build/Dockerfile
Merges: https://github.com/openmpf/openmpf-docker/pull/144
**Issues:**
- https://github.com/openmpf/openmpf/issues/1331
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/145)
=> Update libheif (#144)

activemq/activemq-default.xml
**Issues:**
- https://github.com/openmpf/openmpf/issues/1360
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/149)
=> Remove policyEntry settings from ActiveMQ config file.

README.md, SWARM.md, components/cpp_executor/README.md, components/java_executor/README.md, components/python/README.md
**Issues:**
- https://github.com/openmpf/openmpf/issues/1358
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/148)
=> Update Docker component base image README files to mention pulling from Docker Hub

SWARM.md
**Issues:**
- TiesDB
- https://github.com/openmpf/openmpf/pull/1343
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/147)
=> Mention how to get actual hostname

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/151)
=> Add GitLFSPull to Jenkinsfile

Jenkinsfile
Merges: https://github.com/openmpf/openmpf-docker/pull/151
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/152)
=> hf-merge/jenkins-lfs

Jenkinsfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/154)
=> Remove clone timeout

Jenkinsfile, SWARM.md, docker-compose.components.test.yml, docker-compose.components.yml
**Issues:**
- https://github.com/openmpf/openmpf/issues/1350
- https://github.com/openmpf/openmpf/pull/1388
- https://github.com/openmpf/openmpf-components/pull/272
- https://github.com/openmpf/openmpf-contrib-components/pull/74
- https://github.com/openmpf/openmpf.github.io/pull/135
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/150)
=> removed dlib-face-detection, darknet-detection, and ocv-person-detection

components/python/README.md, components/python/install-component.sh
**Issues:**
- https://github.com/openmpf/openmpf/issues/1431
- https://github.com/openmpf/openmpf-components/pull/285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/155)
=> Update python component Dockerfiles to use readwrite mount for pip 21.3.

docker-compose.elk.yml, kibana/Dockerfile, kibana/docker-entrypoint.sh
**Issues:**
- https://github.com/openmpf/openmpf/issues/1460
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/159)
=> Update elk stack version numbers

docker-compose.elk.yml, kibana/Dockerfile, kibana/docker-entrypoint.sh
Merges: https://github.com/openmpf/openmpf-docker/pull/159
**Issues:**
- https://github.com/openmpf/openmpf/issues/1460
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/160)
=> Update elk stack version numbers (#159)

docker-compose.components.yml
**Issues:**
- https://github.com/openmpf/openmpf/issues/1398
- https://github.com/openmpf/openmpf-components/pull/284
- https://github.com/openmpf/openmpf/pull/1474
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/161)
=> Add service entry for ocv-yolo-detection-server.

integration_tests/Dockerfile, integration_tests/enable-ajp.patch, workflow_manager/Dockerfile
Merges: https://github.com/openmpf/openmpf-docker/pull/163
**Issues:**
- https://github.com/openmpf/openmpf/issues/1514
- https://github.com/openmpf/openmpf.github.io/pull/148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/164)
=> Hf merge/update tomcat

components/cpp_component_build/Dockerfile, openmpf_build/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1519
- https://github.com/openmpf/openmpf/pull/1518
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/112
- https://github.com/openmpf/openmpf-docker/pull/165
- https://github.com/openmpf/openmpf-components/pull/293
- https://github.com/openmpf/openmpf-contrib-components/pull/78
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/165)
=> Hotfix/ocv 4.5.5

components/cpp_component_build/Dockerfile, openmpf_build/Dockerfile
Merges: https://github.com/openmpf/openmpf-docker/pull/165
**Issues:**
- https://github.com/openmpf/openmpf/issues/1519
- https://github.com/openmpf/openmpf/pull/1523
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/113
- https://github.com/openmpf/openmpf-docker/pull/166
- https://github.com/openmpf/openmpf-components/pull/294
- https://github.com/openmpf/openmpf-contrib-components/pull/79
- https://github.com/openmpf/openmpf.github.io/pull/150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/166)
=> Hf merge/ocv 4.5.5

components/cli_runner/mpf_cli_runner.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1528
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/168)
=> Sort CLI runner output by time

activemq/Dockerfile, components/java_component_build/Dockerfile, components/java_executor/Dockerfile, integration_tests/Dockerfile, markup/Dockerfile, openmpf_build/Dockerfile, workflow_manager/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1540
- https://github.com/openmpf/openmpf/pull/1541
- https://github.com/openmpf/openmpf.github.io/pull/151
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/169)
=> Upgrade to Java 17

components/cli_runner/mpf_cli_executor_process.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1561
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/172)
=> Fix cli logging

components/cli_runner/mpf_cli_executor_process.py
Merges: https://github.com/openmpf/openmpf-docker/pull/172
**Issues:**
- https://github.com/openmpf/openmpf/issues/1561
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/173)
=> Merge Fix cli logging

workflow_manager/docker-entrypoint.sh
**Issues:**
- https://github.com/openmpf/openmpf/issues/1595
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/175)
=> Handle certs that don't end with .crt

workflow_manager/docker-entrypoint.sh
Merges: https://github.com/openmpf/openmpf-docker/pull/175
**Issues:**
- https://github.com/openmpf/openmpf/issues/1595
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/176)
=> Hf merge/cert file suffix

activemq/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/181)
=> Upgrade to ActiveMQ 5.17.3

activemq/Dockerfile
Merges: https://github.com/openmpf/openmpf-docker/pull/181
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/182)
=> Hf merge/activemq 5.17.3

Jenkinsfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1635
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/183)
=> Log in to registry when running pre-build script

Jenkinsfile
Merges: https://github.com/openmpf/openmpf-docker/pull/183
**Issues:**
- https://github.com/openmpf/openmpf/issues/1635
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/184)
=> Log in to registry when running pre-build script (#183)

components/cpp_component_build/Dockerfile, openmpf_build/Dockerfile
**Issues**
- https://github.com/openmpf/openmpf/issues/1649
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/185)
=> Install specific version of cudnn

components/cpp_component_build/Dockerfile, openmpf_build/Dockerfile
Merges: https://github.com/openmpf/openmpf-docker/pull/185
**Issues:**
- https://github.com/openmpf/openmpf/issues/1649
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/186)
=> Install specific version of cudnn (#185)

Jenkinsfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1659
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/187)
=> Add options to skip integration tests and prune Docker.

Jenkinsfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1670
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/188)
=>  Add Docker build timeout to Jenkins build

Jenkinsfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1685
- https://github.com/openmpf/openmpf-components/pull/326
- https://github.com/openmpf/openmpf-docker/pull/189
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/192)
=> Remove docker.withRegistry() calls.

Jenkinsfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1689
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/193)
=> Remove --ansi always

Jenkinsfile
Merges: https://github.com/openmpf/openmpf-docker/pull/193
**Issues:**
- https://github.com/openmpf/openmpf/issues/1689
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/194)
=> Remove --ansi always (#193)

docker-compose.components.yml
**Issues:**
- https://github.com/openmpf/openmpf/issues/1547
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/195)
=> adding argos to docker compose

docker-compose.components.yml
**Issues:**
- https://github.com/openmpf/openmpf/issues/1598
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/191)
=> adding whisper

activemq/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1715
- https://github.com/openmpf/openmpf/pull/1716
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/198)
=> Use newer version of ActiveMQ

activemq/Dockerfile
Merges: https://github.com/openmpf/openmpf-docker/pull/198
**Issues:**
- https://github.com/openmpf/openmpf/issues/1715
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/199)
=> Hf merge/amq version

components/component-executor.py
**Issues:**
- https://github.com/openmpf/openmpf/issues/1731
- https://github.com/openmpf/openmpf/pull/1742
- https://github.com/openmpf/openmpf-docker/pull/202
- https://github.com/openmpf/openmpf-components/pull/347
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/202)
=> Forward signal to executor

components/component-executor.py
Merges: https://github.com/openmpf/openmpf-docker/pull/202
**Issues:**
- https://github.com/openmpf/openmpf/issues/1731
- https://github.com/openmpf/openmpf/pull/1746
- https://github.com/openmpf/openmpf-docker/pull/203
- https://github.com/openmpf/openmpf-components/pull/348
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/203)
=> Hf merge/health check

Jenkinsfile, components/python/Dockerfile, trivyignore.txt
**Issues:**
- https://github.com/openmpf/openmpf/issues/1748
- https://github.com/openmpf/openmpf-docker/pull/205
- https://github.com/openmpf/openmpf-components/pull/349
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/205)
=> Address trivy issues

components/cpp_component_build/Dockerfile, openmpf_build/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1785
- 
- https://github.com/openmpf/openmpf/pull/1791
- https://github.com/openmpf/openmpf-components/pull/362
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/123
- https://github.com/openmpf/openmpf-contrib-components/pull/90
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/211)
=> Update build to use OpenCV 4.9.0

components/python/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1798
- https://github.com/openmpf/openmpf-python-component-sdk/pull/78
- https://github.com/openmpf/openmpf-components/pull/364
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/213)
=> Update to use modularized nlp_text_splitter package. 

Jenkinsfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1800
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/215)
=> Enable specifying the Docker images to push.

Jenkinsfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1826
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/218)
=> Parallelize Docker cleanup in Jenkins builds

Jenkinsfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1856
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/226)
=> Get PR refs in Jenkinsfile

Jenkinsfile, workflow_manager/docker-entrypoint.sh
**Merges:**
- https://github.com/openmpf/openmpf-docker/pull/224
- https://github.com/openmpf/openmpf-docker/pull/226
**Issues:**
- https://github.com/openmpf/openmpf-docker/issues/223
- https://github.com/openmpf/openmpf/issues/1856
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/227)
=> Hf merge/use pull req branches

components/python/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1859
- https://github.com/openmpf/openmpf-docker/pull/228
- https://github.com/openmpf/openmpf-components/pull/386
- https://github.com/openmpf/openmpf-python-component-sdk/pull/88
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/228)
=> Install g++ when installing text splitter

docker-compose.components.yml
**Issues:**
- https://github.com/openmpf/openmpf/issues/1679
- https://github.com/openmpf/openmpf-components/pull/387
- https://github.com/openmpf/openmpf.github.io/pull/188
- https://github.com/openmpf/openmpf-component-archive/pull/3
Please review our [Contributor Guide](https://openmpf.github.io/docs/site/Contributor-Guide/index.html).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/229)
=> Retiring Azure OCR Text Detection Component.

openmpf_build/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1903
- https://github.com/openmpf/openmpf/pull/1904
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/240)
=> Add AVIF support.

docker-compose.components.yml
**Issues:**
- https://github.com/openmpf/openmpf/issues/1883
- https://github.com/openmpf/openmpf-components/pull/398
- https://github.com/openmpf/openmpf-docker/pull/243
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/243)
=> Add LLaMA video summarization component.

README.md, components/cpp_component_build/Dockerfile, components/cpp_executor/Dockerfile, components/java_component_build/Dockerfile, components/python/Dockerfile, docker-bake.hcl
**Issues:**
- https://github.com/openmpf/openmpf/issues/1863
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/232)
=> Add docker-bake.hcl

components/cpp_executor/Dockerfile, components/python/Dockerfile, markup/Dockerfile, openmpf_build/Dockerfile, openmpf_build/scripts/copy_libs.sh, workflow_manager/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1930
- https://github.com/openmpf/openmpf/pull/1941
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/247)
=> Installing headers and libraries needed to build heif JNI library

openmpf_build/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1950
- https://github.com/openmpf/openmpf/pull/1952
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/249)
=> updated libheif to v1.20.2

openmpf_build/Dockerfile
**Issues:**
- https://github.com/openmpf/openmpf/issues/1950
- https://github.com/openmpf/openmpf/pull/1954
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/250)
=> Hf merge/libheif update

Jenkinsfile, docker-compose.core.yml, docker-compose.integration.test.yml
**Issues:**
- https://github.com/openmpf/openmpf/issues/1970
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/openmpf/openmpf-docker/252)
=> Use postgres:17-alpine
